# Generated by Django 4.2.5 on 2023-11-05 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_attendence_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='enroll',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seat',
            name='raise_hand',
            field=models.BooleanField(default=False),
        ),
    ]
