# Generated by Django 4.2.5 on 2023-11-05 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_alter_seat_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='students_online',
            field=models.ManyToManyField(blank=True, related_name='online_room', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='teacher_online',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='online_tea', to=settings.AUTH_USER_MODEL),
        ),
    ]
